env:
 global:
  - secure: TaDnMoV1QdFT0i30fFMLgIFG8xCVxG70t9Qht6BtKlYmVtly1e35Ee4UfQuF8KAo0jmpQNdhX/dUkkp9vJDyhmjtGBL/l8yaNoFaLF5ilIHZR2dAu1KCvJp+gkuSVXEq/7HwSI4//ehJTI6DdzwC+wFQcNNoDt9O/VVSpGJJvE1vWcnWGTCjq4UekjPbA/xeAa0HW/EiTIcjx5XIloOFirNkcfhN0mvM7D0Uy2QcfFKLmS3MsTjIkgkAu7kwJbD2gR5hxYjWKfudfD2kqRKYbSIgzB+J/fBzarxhPDX2lEz/3HWNcq/yR6POEf3gqdhbmNsLoXeVrURX9qOmhoIh+4NtEMvaogCCOfc43swJQ2sqAX8RchV9zP6i9ueQ7V+XA5uJO2QjcFXStqe6i8sBZn4pwzcm3ATVNrWfh8YlaC5aNxb0cRYadKAQNYCNYF31p6saghbydv45FiYfYfMzUf9zGrSJiTo4WV/CHPL26p/qUXvdxAcKwzqWM5cvdogm2FWL+o57KC4ZgNV4B3cdfz6GDk6zk1vRRsjDHzIxtSFJfOn44NQaI4wG81JrIyL/EPPazqvqXUhSCLwOy7uuWhkSeEnbAVZtnwLqDQ9fNwgBfNjQ2q43HEkyyenAZc3nrjLlRFIbW08hb2Uue+IYN4iX08BGUdied2K9SPbIXh4=
  - secure: VdnNlIXEaIXNQOWAOzOBg89c0YeK8Ad7ldYthdR6avTcOysZy+9brgvV7FJG8ejOVDbU5vCDNaJqRK7GvsO2VjdllBSvYMhSR3L6tBtue+cCDz291yFfIBZl8BP8IZz5onou583a/EtlXMbZSU4TQB32g3FHD4w12JojGonAmI/FbvwQ6engVpZ0JUZkY5xJiwKk4A2TBtmsADahdNOuDe9Kw9r5YWZ2O57gu9ZjWaeffxbgJAbWM1rAvJUjPyTMnvGb/3MFmigCZ9GnBejYLELsHKDwUo/A40eZrUYia51cpzwVEdo2I7bwfhcjQT9VjI0pNIbShETnTP8Bd3Z/tY0jcM41SsQELVWlgVI/z5QDmReH9aKAj3qkHFs8ONnWwWfdMhjE2fzBSUJwz8EZnrln2cpe9kuhMFXk0384gzj3uKq5ebiJNPoNkcexmQdKkgPOuOweP+KQTq333R7G+8UHRpYkc/CjfViBbxKAooqQCTPt+vZuszEDSOlcGUlpaH+vEiq0vPGaWTStcj+rUYUvPOwVLtJzaIwa14alseO4L/kWPagMuH8wI6bTVPWVYsbgAuzOyi7eBgyY33WdW2S0NyoQXpkuVfJycx6wcgwGj20Jm+waGZJ4YCECPEEHIIzQw5NhYs0gLxOBpjCd9T/cN7i71Adrg/qWQUM+njE=

os:
 - linux
 - osx

language: java
install: true

script:
 - if [ $TRAVIS_OS_NAME == "osx" ]; then
    chmod +x ./prepare-mac.sh;
    ./prepare-mac.sh;
   fi
 - if [ $TRAVIS_OS_NAME == "linux" ]; then
    chmod +x ./prepare-linux.sh;
    ./prepare-linux.sh;
   fi

deploy:
 - provider: bintray
   file: deploy-deb.json
   user: aarrsseni
   key:
    secure: SnQXLgjgKs+LSXOBAuy0zSe80fozN5250Yo/n5Uj80r7CHkSuqYQM4EpL05CcAdRVzxW7huixY5HMmFj3V5DazsMrwJA+8Dh/+D6CNs65VgoeJQtCMBKbboMSbaA7lozOupr6ixNtX5x/jXUQSHUF7LN/n5uA1EH3qkn2QmkT/g6+MBCkD5O622ClhXKL6D9LBo1H4VGL43MtPlea91LMhTzhwk4xmnVgJ6u0wHF+M4QDR7yNHlgQHEjxAHG+t4sresTcisjXyQlQ1DO6MdRs3KgqhWkFkj+pWNzDdguYxmVyozVwplAAOZu7eIgxkse1inWpylQ13LIau7Nb0pdjZO7kdkQDhY8sqIsb/6OFTidwydoUHhvYZkD8Ol63NUVuNmYv1IxZjg4h8MKhGjRYt/eFA41qIFpyHMrVrHXZpPyBH9Vo629jWZGPJrMzyk1zCXOTkBUG6Zx2EOkHGbYuT9wgJe0CUwXM1tRCXusgHcFGq1HiKDXinq1H3d/XOqVBsubN8Xj7fNw4UfJq9MzWEoBnX5OXBQPM4bUsHc8eDWutpPfjS9WmibGQfZf8/U97PFn8a7pPTPkt348tjiCiC1FoDNS5FFsfvbO5fGhLdErSHapZSRqTVlHleonDbkKEBjNxqMh60PYWR3BfemLqfFtBTeG+Qu8EqJsQtMNM9A=
   skip_cleanup: true
   on:
    branch: master
    condition: $TRAVIS_OS_NAME == "linux"
    tags: true
 - provider: bintray
   file: deploy-rpm.json
   user: aarrsseni
   key:
    secure: SnQXLgjgKs+LSXOBAuy0zSe80fozN5250Yo/n5Uj80r7CHkSuqYQM4EpL05CcAdRVzxW7huixY5HMmFj3V5DazsMrwJA+8Dh/+D6CNs65VgoeJQtCMBKbboMSbaA7lozOupr6ixNtX5x/jXUQSHUF7LN/n5uA1EH3qkn2QmkT/g6+MBCkD5O622ClhXKL6D9LBo1H4VGL43MtPlea91LMhTzhwk4xmnVgJ6u0wHF+M4QDR7yNHlgQHEjxAHG+t4sresTcisjXyQlQ1DO6MdRs3KgqhWkFkj+pWNzDdguYxmVyozVwplAAOZu7eIgxkse1inWpylQ13LIau7Nb0pdjZO7kdkQDhY8sqIsb/6OFTidwydoUHhvYZkD8Ol63NUVuNmYv1IxZjg4h8MKhGjRYt/eFA41qIFpyHMrVrHXZpPyBH9Vo629jWZGPJrMzyk1zCXOTkBUG6Zx2EOkHGbYuT9wgJe0CUwXM1tRCXusgHcFGq1HiKDXinq1H3d/XOqVBsubN8Xj7fNw4UfJq9MzWEoBnX5OXBQPM4bUsHc8eDWutpPfjS9WmibGQfZf8/U97PFn8a7pPTPkt348tjiCiC1FoDNS5FFsfvbO5fGhLdErSHapZSRqTVlHleonDbkKEBjNxqMh60PYWR3BfemLqfFtBTeG+Qu8EqJsQtMNM9A=
   skip_cleanup: true
   on:
    branch: master
    condition: $TRAVIS_OS_NAME == "linux"
    tags: true
 - provider: bintray
   file: deploy-mac.json
   user: aarrsseni
   key:
    secure: SnQXLgjgKs+LSXOBAuy0zSe80fozN5250Yo/n5Uj80r7CHkSuqYQM4EpL05CcAdRVzxW7huixY5HMmFj3V5DazsMrwJA+8Dh/+D6CNs65VgoeJQtCMBKbboMSbaA7lozOupr6ixNtX5x/jXUQSHUF7LN/n5uA1EH3qkn2QmkT/g6+MBCkD5O622ClhXKL6D9LBo1H4VGL43MtPlea91LMhTzhwk4xmnVgJ6u0wHF+M4QDR7yNHlgQHEjxAHG+t4sresTcisjXyQlQ1DO6MdRs3KgqhWkFkj+pWNzDdguYxmVyozVwplAAOZu7eIgxkse1inWpylQ13LIau7Nb0pdjZO7kdkQDhY8sqIsb/6OFTidwydoUHhvYZkD8Ol63NUVuNmYv1IxZjg4h8MKhGjRYt/eFA41qIFpyHMrVrHXZpPyBH9Vo629jWZGPJrMzyk1zCXOTkBUG6Zx2EOkHGbYuT9wgJe0CUwXM1tRCXusgHcFGq1HiKDXinq1H3d/XOqVBsubN8Xj7fNw4UfJq9MzWEoBnX5OXBQPM4bUsHc8eDWutpPfjS9WmibGQfZf8/U97PFn8a7pPTPkt348tjiCiC1FoDNS5FFsfvbO5fGhLdErSHapZSRqTVlHleonDbkKEBjNxqMh60PYWR3BfemLqfFtBTeG+Qu8EqJsQtMNM9A=
   skip_cleanup: true
   on:
    branch: master
    condition: $TRAVIS_OS_NAME == "osx"
    tags: true

after_deploy:
 - if [ $TRAVIS_OS_NAME == "osx" ]; then
  chmod +x ./update-homebrew.sh;
  ./update-homebrew.sh;
  fi



