environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\run_with_env.cmd"

init:
  - cinst graalvm
  - set PATH=C:\Program Files\GraalVM\graalvm-ce-19.1.0\bin;%PATH%

image: Previous Visual Studio 2013

build_script:
  - mvn clean install
#  - native-image -jar target\release-test-1.52-SNAPSHOT.jar -H:Name=release-test

test_script:
  - "%WITH_COMPILER% native-image -jar target\release-test-1.52-SNAPSHOT.jar -H:Name=release-test"