init:
  - cinst graalvm
  - set PATH=C:\Program Files\GraalVM\graalvm-ce-19.1.0\bin;%PATH%
  - set JAR_NAME=test

image: Visual Studio 2015

build_script:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - mvn clean install
  - for /f %%i in ('dir /b target\release-test-*.jar') do set JAR_NAME=%%i
  - native-image -jar target\%JAR_NAME% -H:Name=release-test
  - mvn clean package -P assembly

artifacts:
  - path: target/*.zip

deploy:
  - provider: BinTray
    username: aarrsseni
    api_key:
      secure: W4G0fUsOMO7GJnB11jQ2Cw1EgT04ktLq9MNfMAzQqZC+dNlI3dM7XGnzLXvuJmMW
    subject: aarrsseni
    repo: release-test-win
    package: release-win
    version: 1.53
    publish: true
    override: true
    explode: true
    on:
      APPVEYOR_REPO_TAG: true # keep casing this way for Linux builds where variables are case-sensitive